Repository Team-KIN/Forest-Server, pull requests merged in 2023-12, with the labels that each got.

#5 4 :: 도메인 세팅
  src/main/kotlin/team/kin/forest/domain/comment/persistence/entity/CommentJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/comment/persistence/repository/CommentRepository.kt
  src/main/kotlin/team/kin/forest/domain/group/persistence/entity/GroupJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/group/persistence/enums/GroupScope.kt
  src/main/kotlin/team/kin/forest/domain/group/persistence/repository/PostReposity.kt
  src/main/kotlin/team/kin/forest/domain/post/persistence/entity/PostJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/post/persistence/enums/PostTag.kt
  src/main/kotlin/team/kin/forest/domain/post/persistence/repository/PostRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/persistence/entity/CompleteJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/todo/persistence/entity/PrivateTodoJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/todo/persistence/entity/PublicTodoJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/todo/persistence/enums/TodoStatus.kt
  src/main/kotlin/team/kin/forest/domain/todo/persistence/repository/CompleteRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/persistence/repository/PrivateTodoRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/persistence/repository/PublicTodoRepository.kt
  src/main/kotlin/team/kin/forest/domain/user/persistence/entity/UserJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/user/persistence/repository/UserRepository.kt
  src/main/kotlin/team/kin/forest/global/entity/BaseTimeEntity.kt
  src/main/kotlin/team/kin/forest/global/entity/BaseUUIDEntity.kt
Labels: ✨ Feature, 🛠 Setting, 1️⃣ High

#8 7 게시글과 댓글 제한 변경
  src/main/kotlin/team/kin/forest/domain/comment/persistence/entity/CommentJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/post/persistence/entity/PostJpaEntity.kt
Labels: 👀 Simple, 1️⃣ High

#14 12 :: 로그인 기능 구현
  build.gradle.kts
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/AuthWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/data/request/SignInRequest.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/data/response/TokenResponse.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/mapper/AuthDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/CommandRefreshTokenPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/QueryUserPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/entity/RefreshTokenEntity.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/entity/UserJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/mapper/RefreshTokenMapper.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/mapper/UserMapper.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/repository/RefreshTokenRepository.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/repository/UserRepository.kt
  src/main/kotlin/team/kin/forest/domain/user/application/event/SaveRefreshTokenEvent.kt
  src/main/kotlin/team/kin/forest/domain/user/application/event/SaveRefreshTokenEventHandler.kt
  src/main/kotlin/team/kin/forest/domain/user/application/exception/DuplicateUserEmailException.kt
  src/main/kotlin/team/kin/forest/domain/user/application/exception/PasswordNotMatchException.kt
  src/main/kotlin/team/kin/forest/domain/user/application/exception/UserNotFoundException.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/SignInUseCase.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/dto/SignInDto.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/CommandRefreshTokenPort.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/PasswordEncodePort.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/QueryUserPort.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/TokenGeneratePort.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/dto/TokenDto.kt
  src/main/kotlin/team/kin/forest/domain/user/application/service/SignInService.kt
  src/main/kotlin/team/kin/forest/domain/user/application/service/SignUpService.kt
  src/main/kotlin/team/kin/forest/domain/user/domain/Authority.kt
  src/main/kotlin/team/kin/forest/domain/user/domain/RefreshToken.kt
  src/main/kotlin/team/kin/forest/domain/user/domain/User.kt
  src/main/kotlin/team/kin/forest/global/config/PropertiesScanConfig.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/adapter/PasswordEncodeAdapter.kt
  src/main/kotlin/team/kin/forest/global/security/token/TokenGenerateAdapter.kt
  src/main/kotlin/team/kin/forest/global/security/token/common/JwtExpTimeProperties.kt
  src/main/kotlin/team/kin/forest/global/security/token/common/JwtProperties.kt
  src/main/resources/application.yml
Labels: ✨ Feature, 1️⃣ High

#15 그룹 조회 api
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/GroupWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/data/response/QueryGroupDetailsResponse.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/data/response/QueryGroupsResponse.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/mapper/GroupDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/QueryGroupPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/QueryMemberPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/mapper/GroupMapper.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/repository/GroupRepository.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/repository/MemberRepository.kt
  src/main/kotlin/team/kin/forest/domain/group/application/exception/GroupNotFoundException.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/input/QueryGroupDetailsUseCase.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/input/QueryGroupsUseCase.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/QueryGroupPort.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/QueryMemberPort.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/dto/GroupDetailsDto.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/dto/GroupsDto.kt
  src/main/kotlin/team/kin/forest/domain/group/domain/Group.kt
  src/main/kotlin/team/kin/forest/domain/group/service/QueryGroupDetailsService.kt
  src/main/kotlin/team/kin/forest/domain/group/service/QueryGroupsService.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/QueryTodoPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/repository/TodoRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/QueryTodoPort.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 1️⃣ High

#19 17 :: 토큰 재발급 api
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/AuthWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/QueryRefreshTokenPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/QueryUserPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/mapper/RefreshTokenMapper.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/ReissueTokenUseCase.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/QueryRefreshTokenPort.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/QueryUserPort.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/TokenParsePort.kt
  src/main/kotlin/team/kin/forest/domain/user/application/service/ReissueTokenService.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/config/FilterConfig.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
  src/main/kotlin/team/kin/forest/global/security/filter/ExceptionHandlerFilter.kt
  src/main/kotlin/team/kin/forest/global/security/filter/JwtRequestFilter.kt
  src/main/kotlin/team/kin/forest/global/security/principal/AccountDetails.kt
  src/main/kotlin/team/kin/forest/global/security/principal/AccountDetailsService.kt
  src/main/kotlin/team/kin/forest/global/security/token/TokenParseAdapter.kt
  src/main/kotlin/team/kin/forest/global/security/token/common/exception/ExpiredRefreshTokenException.kt
  src/main/kotlin/team/kin/forest/global/security/token/common/exception/InvalidTokenException.kt
  src/main/kotlin/team/kin/forest/global/security/token/common/exception/InvalidTokenTypeException.kt
Labels: ✨ Feature, 1️⃣ High

#21 메인 페이지 조회 api 작성
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/QueryMemberPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/repository/MemberRepository.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/QueryMemberPort.kt
  src/main/kotlin/team/kin/forest/domain/main/adapter/input/MainWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/main/adapter/input/data/response/QueryMainResponse.kt
  src/main/kotlin/team/kin/forest/domain/main/adapter/input/mapper/MainDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/main/port/input/QueryMainUseCase.kt
  src/main/kotlin/team/kin/forest/domain/main/port/output/dto/MainDto.kt
  src/main/kotlin/team/kin/forest/domain/main/service/QueryMainService.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/QueryUserPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/QueryUserPort.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/SecurityPort.kt
  src/main/kotlin/team/kin/forest/global/security/adapter/SecurityAdapter.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 1️⃣ High

#23 그룹 개설 api
  build.gradle.kts
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/GroupWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/data/request/CreateGroupRequest.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/data/response/GroupCodeResponse.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/mapper/GroupDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/CommandGroupPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/CommandMemberPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/mapper/MemberMapper.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/repository/MemberRepository.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/input/CreateGroupUseCase.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/input/dto/CreateGroupDto.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/CommandGroupPort.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/CommandMemberPort.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/dto/GroupCodeDto.kt
  src/main/kotlin/team/kin/forest/domain/group/domain/Member.kt
  src/main/kotlin/team/kin/forest/domain/group/service/CreateGroupService.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 1️⃣ High

#24 그룹 가입 api
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/GroupWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/data/request/GroupCodeRequest.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/input/mapper/GroupDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/QueryGroupPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/QueryMemberPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/repository/GroupRepository.kt
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/repository/MemberRepository.kt
  src/main/kotlin/team/kin/forest/domain/group/application/exception/AlreadyJoinGroupException.kt
  src/main/kotlin/team/kin/forest/domain/group/application/exception/PrivateGroupException.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/input/JoinGroupByCodeUseCase.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/input/JoinGroupUseCase.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/input/dto/GroupCodeDto.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/QueryGroupPort.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/QueryMemberPort.kt
  src/main/kotlin/team/kin/forest/domain/group/service/JoinGroupByCodeService.kt
  src/main/kotlin/team/kin/forest/domain/group/service/JoinGroupService.kt
  src/main/kotlin/team/kin/forest/domain/group/service/QueryGroupDetailsService.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 1️⃣ High

#26 마이페이지 조회 api
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/UserWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/data/response/UserResponse.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/mapper/UserDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/QueryMyPageUseCase.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/dto/UserDto.kt
  src/main/kotlin/team/kin/forest/domain/user/application/service/QueryMyPageService.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 2️⃣ Midium

#30 29 :: 로그아웃 api
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/AuthWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/CommandRefreshTokenPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/LogoutUserUseCase.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/output/CommandRefreshTokenPort.kt
  src/main/kotlin/team/kin/forest/domain/user/application/service/LogoutUserService.kt
Labels: ✨ Feature, 2️⃣ Midium

#34 개인 투두 작성 api
  src/main/kotlin/team/kin/forest/domain/group/adapter/output/persistence/mapper/MemberMapper.kt
  src/main/kotlin/team/kin/forest/domain/group/application/exception/MemberNotFoundException.kt
  src/main/kotlin/team/kin/forest/domain/group/application/port/output/QueryMemberPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/TodoWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/CommandPrivateTodoPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/CommandTodoPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/entity/PrivateTodoJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/entity/TodoJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/mapper/PrivateTodoMapper.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/mapper/TodoMapper.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/WritePrivateTodoUseCase.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/CommandPrivateTodoPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/CommandTodoPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/service/WritePrivateTodoService.kt
  src/main/kotlin/team/kin/forest/domain/todo/domain/PrivateTodo.kt
  src/main/kotlin/team/kin/forest/domain/todo/domain/Todo.kt
  src/main/kotlin/team/kin/forest/domain/user/application/service/SignUpService.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
Labels: ✨ Feature, 1️⃣ High

#35 게시글 조회 api
  src/main/kotlin/team/kin/forest/common/annotation/MemberOnly.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/output/persistence/QueryCommentPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/output/persistence/mapper/CommentMapper.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/output/persistence/repository/CommentRepository.kt
  src/main/kotlin/team/kin/forest/domain/comment/application/port/output/QueryCommentPort.kt
  src/main/kotlin/team/kin/forest/domain/comment/domain/Comment.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/PostWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/data/QueryPostDetailsResponse.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/data/QueryPostsResponse.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/mapper/CommentDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/mapper/PostDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/output/QueryPostPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/output/persistence/mapper/PostMapper.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/output/persistence/repository/PostRepository.kt
  src/main/kotlin/team/kin/forest/domain/post/application/exception/PostNotFoundException.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/input/QueryPostDetailsUseCase.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/input/QueryPostsUseCase.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/output/QueryPostPort.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/output/dto/CommentDto.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/output/dto/PostDetailsDto.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/output/dto/PostsDto.kt
  src/main/kotlin/team/kin/forest/domain/post/domain/Post.kt
  src/main/kotlin/team/kin/forest/domain/post/service/QueryPostDetailsService.kt
  src/main/kotlin/team/kin/forest/domain/post/service/QueryPostsService.kt
  src/main/kotlin/team/kin/forest/global/aop/MemberOnlyAspect.kt
  src/main/kotlin/team/kin/forest/global/aop/exception/NotGroupMemberException.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 2️⃣ Midium

#32 유저 정보 변경 api
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/UserWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/data/request/ModifyUserNameRequest.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/data/request/ModifyUserPasswordRequest.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/data/request/ModifyUserProfileUrlRequest.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/input/mapper/UserDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/user/adapter/output/persistence/entity/UserJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/ModifyUserNameUseCase.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/ModifyUserPasswordUseCase.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/ModifyUserProfileUrlUseCase.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/dto/ModifyUserNameDto.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/dto/ModifyUserPasswordDto.kt
  src/main/kotlin/team/kin/forest/domain/user/application/port/input/dto/ModifyUserProfileUrlDto.kt
  src/main/kotlin/team/kin/forest/domain/user/application/service/ModifyUserNameService.kt
  src/main/kotlin/team/kin/forest/domain/user/application/service/ModifyUserPasswordService.kt
  src/main/kotlin/team/kin/forest/domain/user/application/service/ModifyUserProfileUrlService.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 2️⃣ Midium

#37 공통 투두 api
  src/main/kotlin/team/kin/forest/domain/group/application/exception/NotGroupManagerException.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/TodoWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/WritePublicTodoUseCase.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/service/WritePublicTodoService.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 1️⃣ High

#41 투두 리스트 조회 api
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/TodoWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/data/request/CreateTodoRequest.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/data/response/TodoListResponse.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/mapper/TodoDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/QueryCompletePersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/QueryPrivateTodoPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/QueryTodoPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/entity/TodoJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/mapper/PrivateTodoMapper.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/mapper/TodoMapper.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/repository/CompleteRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/repository/PrivateTodoRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/repository/TodoRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/QueryTodoListUseCase.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/WritePrivateTodoUseCase.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/WritePublicTodoUseCase.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/dto/CreateTodoDto.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/dto/TodoListDto.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/QueryCompletePort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/QueryPrivateTodoPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/QueryTodoPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/service/QueryTodoListService.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/service/WritePrivateTodoService.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/service/WritePublicTodoService.kt
  src/main/kotlin/team/kin/forest/domain/todo/domain/Todo.kt
Labels: ✨ Feature, 1️⃣ High

#40 39 게시글 및 댓글 생성 api
  src/main/kotlin/team/kin/forest/domain/comment/adapter/input/CommentWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/input/data/request/CreateCommentRequest.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/input/mapper/CommentDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/output/persistence/CommendCommentPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/output/persistence/mapper/CommentMapper.kt
  src/main/kotlin/team/kin/forest/domain/comment/application/port/input/CreateCommentUseCase.kt
  src/main/kotlin/team/kin/forest/domain/comment/application/port/input/dto/CreateCommentDto.kt
  src/main/kotlin/team/kin/forest/domain/comment/application/port/output/CommendCommentPort.kt
  src/main/kotlin/team/kin/forest/domain/comment/service/CreateCommentService.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/PostWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/data/request/CreatePostRequest.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/data/response/QueryPostDetailsResponse.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/data/response/QueryPostsResponse.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/mapper/PostDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/output/persistence/CommendPostPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/output/persistence/QueryPostPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/output/persistence/mapper/PostMapper.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/input/CreatePostUseCase.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/output/CommendPostPort.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/output/dto/CreatePostDto.kt
  src/main/kotlin/team/kin/forest/domain/post/service/CreatePostService.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 2️⃣ Midium

#44 게시글 수정 api
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/PostWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/data/request/ModifyPostRequest.kt
  src/main/kotlin/team/kin/forest/domain/post/adapter/input/mapper/PostDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/post/application/exception/ForbiddenPostException.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/input/CreatePostUseCase.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/input/ModifyPostUseCase.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/input/dto/CreatePostDto.kt
  src/main/kotlin/team/kin/forest/domain/post/application/port/input/dto/ModifyPostDto.kt
  src/main/kotlin/team/kin/forest/domain/post/service/CreatePostService.kt
  src/main/kotlin/team/kin/forest/domain/post/service/ModifyPostService.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 1️⃣ High

#46 댓글 수정 api
  src/main/kotlin/team/kin/forest/domain/comment/adapter/input/CommentWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/input/data/request/ModifyCommentRequest.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/input/mapper/CommentDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/comment/adapter/output/persistence/QueryCommentPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/comment/application/exception/CommentNotFoundException.kt
  src/main/kotlin/team/kin/forest/domain/comment/application/exception/ForbiddenCommentException.kt
  src/main/kotlin/team/kin/forest/domain/comment/application/port/input/ModifyCommentUseCase.kt
  src/main/kotlin/team/kin/forest/domain/comment/application/port/input/dto/ModifyCommentDto.kt
  src/main/kotlin/team/kin/forest/domain/comment/application/port/output/QueryCommentPort.kt
  src/main/kotlin/team/kin/forest/domain/comment/service/ModifyCommentService.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 1️⃣ High

#47 38 투두 완료 api
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/TodoWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/CommandCompleteTodoPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/QueryCompletePersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/QueryPrivateTodoPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/QueryTodoPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/entity/CompleteTodoJpaEntity.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/mapper/CompleteTodoMapper.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/repository/CompleteTodoRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/repository/PrivateTodoRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/repository/TodoRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/exception/AlreadyCompleteTodoException.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/exception/TodoNotFoundException.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/CompletePrivateTodoUseCase.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/CompleteTodoUseCase.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/CommandCompleteTodoPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/QueryCompleteTodoPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/QueryPrivateTodoPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/QueryTodoPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/service/CompletePrivateTodoService.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/service/CompleteTodoService.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/service/QueryTodoListService.kt
  src/main/kotlin/team/kin/forest/domain/todo/domain/CompleteTodo.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 1️⃣ High

#49 48 투두 수정 api
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/TodoWebAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/data/request/ModifyTodoRequest.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/input/mapper/TodoDataMapper.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/QueryPrivateTodoPersistenceAdapter.kt
  src/main/kotlin/team/kin/forest/domain/todo/adapter/output/persistence/repository/PrivateTodoRepository.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/exception/NotTodoOwnerException.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/ModifyTodoUseCase.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/input/dto/ModifyTodoDto.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/port/output/QueryPrivateTodoPort.kt
  src/main/kotlin/team/kin/forest/domain/todo/application/service/ModifyTodoService.kt
  src/main/kotlin/team/kin/forest/domain/todo/domain/CompleteTodo.kt
  src/main/kotlin/team/kin/forest/domain/todo/domain/PrivateTodo.kt
  src/main/kotlin/team/kin/forest/domain/todo/domain/Todo.kt
  src/main/kotlin/team/kin/forest/global/error/ErrorCode.kt
  src/main/kotlin/team/kin/forest/global/security/config/SecurityConfig.kt
Labels: ✨ Feature, 3️⃣ Low
